## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則話來觀察訓練情形。

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# 忽略警告訊息
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Linear regssion
# Load and return the boston house-prices dataset (regression).
boston = datasets.load_boston()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=6)

In [3]:
# 建立一個線性回歸模型
regr = linear_model.LinearRegression()

# 將訓練資料丟進去模型訓練
regr.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)

# 可以看回歸模型的參數值
print('Coefficients: ', regr.coef_)

# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

print("R2 Score: %.2f"
      % r2_score(y_test, y_pred))

Coefficients:  [-8.37706234e-02  5.26973316e-02 -2.99091142e-02  2.80173966e+00
 -1.53320954e+01  3.36056709e+00  6.03391959e-03 -1.57441516e+00
  3.48136303e-01 -1.48030305e-02 -9.87156291e-01  9.21978712e-03
 -5.70626081e-01]
Mean squared error: 27.22
R2 Score: 0.68


In [4]:
# 建立一個線性回歸模型+L1
lasso = linear_model.Lasso(alpha=0.5)

# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)

# 可以看回歸模型的參數值
print('Coefficients: ', lasso.coef_)

# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

print("R2 Score: %.2f"
      % r2_score(y_test, y_pred))

Coefficients:  [-0.06615252  0.05379529 -0.05212977  0.         -0.          2.01637761
  0.00877362 -1.08844825  0.33274825 -0.01774548 -0.84375403  0.00878428
 -0.69882022]
Mean squared error: 30.96
R2 Score: 0.64


In [5]:
# 建立一個線性回歸模型+L2
ridge = linear_model.Ridge(alpha=0.5)

# 將訓練資料丟進去模型訓練
ridge.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = ridge.predict(x_test)

# 可以看回歸模型的參數值
print('Coefficients: ', ridge.coef_)

# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

print("R2 Score: %.2f"
      % r2_score(y_test, y_pred))

Coefficients:  [-8.09578085e-02  5.30433220e-02 -4.81005075e-02  2.71629959e+00
 -1.09403426e+01  3.38516303e+00  2.08367326e-03 -1.50785766e+00
  3.38188056e-01 -1.51555924e-02 -9.41293636e-01  9.38795376e-03
 -5.77041105e-01]
Mean squared error: 27.63
R2 Score: 0.68


In [6]:
# Linear regssion
# Load and return the linnerud dataset (multivariate regression).
linnerud = datasets.load_linnerud()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(linnerud.data, linnerud.target, test_size=0.2, random_state=6)

In [7]:
# 建立一個線性回歸模型
regr = linear_model.LinearRegression()

# 將訓練資料丟進去模型訓練
regr.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)

# 可以看回歸模型的參數值
print('Coefficients: ', regr.coef_)

# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

print("R2 Score: %.2f"
      % r2_score(y_test, y_pred))

Coefficients:  [[-0.86100428 -0.17470426  0.08213836]
 [-0.1781998  -0.03726372  0.02649175]
 [-0.07229078  0.06398569 -0.03819989]]
Mean squared error: 93.17
R2 Score: -0.39


In [8]:
# 建立一個線性回歸模型+L1
lasso = linear_model.Lasso(alpha=2)

# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)

# 可以看回歸模型的參數值
print('Coefficients: ', lasso.coef_)

# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

print("R2 Score: %.2f"
      % r2_score(y_test, y_pred))

Coefficients:  [[-0.73837085 -0.18069304  0.08039082]
 [-0.05552421 -0.04325546  0.02474456]
 [-0.          0.05780417 -0.03606672]]
Mean squared error: 90.46
R2 Score: -0.29


In [9]:
# 建立一個線性回歸模型+L2
ridge = linear_model.Ridge(alpha=0.5)

# 將訓練資料丟進去模型訓練
ridge.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = ridge.predict(x_test)

# 可以看回歸模型的參數值
print('Coefficients: ', ridge.coef_)

# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

print("R2 Score: %.2f"
      % r2_score(y_test, y_pred))

Coefficients:  [[-0.85926653 -0.17480923  0.08213817]
 [-0.17784032 -0.03728531  0.02649151]
 [-0.07213466  0.06397458 -0.0381981 ]]
Mean squared error: 93.14
R2 Score: -0.39
